services:
  app:
    build:
      context: .
    ports:
      - "3000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
      - /app/node_modules
    restart: on-failure
    command:
      - sh -c "npm start"

  project-postgres-db:
    image: postgres:16.1
    ports:
      - '5433:5432'
    env_file:
      - ./backend/.env
    volumes:
      - project-for-school-api-db:/var/lib/postgresql/data
    restart: on-failure
    healthcheck:
      test: ["CMD","pg_isready","-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  project-redis:
    image: redis:7.2.3
    ports:
      - '${REDIS_PORT:-6379}:6379'
    command: >
      --requirepass '${REDIS_PASSWORD:-rpass}'
    restart: unless-stopped
    healthcheck:
      test: ["CMD","redis-cli", "ping"]

  project-s3:
    image: quay.io/minio/minio:latest
    command: server /data --console-address ":9001"
    restart: unless-stopped
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - project-for-school-api-s3-data:/usr/src/app/s3
    environment:
      - MINIO_ROOT_USER=user
      - MINIO_ROOT_PASSWORD=password

volumes:
  project-for-school-api-db:
  project-for-school-api-s3-data:








